### ISSUE TITLE
What would the production start script be?

### ISSUE THREAD

**Issue by MrGigabit** [lukemcdonald/holly-react#12]
I want to deploy this on heroku, what would the script be to start the production server?

**Comment by MusaAqeel** [comment]
> I want to deploy this on heroku, what would the script be to start the production server?

hey, did you find the solution? @MrGigabit

**Comment by lukemcdonald** [comment]
That's a good question. I believe deploying a React application on Heroku may require a server to serve your built files. While I haven't worked with Heroku much I did find some information that might be helpful and get you pointed in the right direction.

1. Consider setting up a small [Express.js server](https://expressjs.com/en/starter/hello-world.html) to serve the files. This will require adding "express" in your ﻿dependencies in ﻿`package.json`.
2. Might need a [Procfile for Heroku](https://devcenter.heroku.com/articles/procfile). e.g. `web: node server.js`
3. May need to update the start script for Heroku: `"start": "node server.js"`
4. May need to add a post install script to build the files for Heroku: `"postinstall": "npm run build"`

If you run into issues, I'd recommend reviewing Heroku's [Deployment Guide for Node.js Applications](https://devcenter.heroku.com/articles/deploying-nodejs) which may be helpful.
