### ISSUE TITLE
Where is the form validation code?

### ISSUE THREAD

**Issue by entangledloops** [lukemcdonald/holly-react#30]
I'm wondering where the logic for detecting whether emails contain an "@", etc. is hidden.

I don't see it inside `NewsletterForm` like I'd expect.

I want to modify it because I don't like that it throws an error message at users who forgot an "@" after they type every character.

**Comment by lukemcdonald** [comment]
@entangledloops You can remove the `type` [attribute](https://github.com/lukemcdonald/holly-react/blob/main/src/components/newsletter-form/newsletter-form.tsx#L43) from the email input.
