### ISSUE TITLE
Style.css being overwritten

### ISSUE THREAD

**Issue by holmesjustin** [lukemcdonald/holly-react#5]
Hello Luke,

I love the repo and have been able to use it to help improve my skills by customizing the site (I am new to React and JS). I have a quick question for you -- when I change the style.css file, it is reflected on the local version of my website, but as soon as I run NPM start again, that file is overwritten with the original version, and my changes are lost. Do you know how I can fix this so the changes I make to the style.css file are not overwritten?

Thanks so much!
Justin

**Comment by lukemcdonald** [comment]
Hi @holmesjustin! 

You may have already figured this one out, but if not, it sounds like you may need to add your customizations to the `assets/css/scss/style.scss` file. This file will be compiled after running `npm start` and upon saving the file. The changes there will not be overwritten when starting or building the site in the future.
