### ISSUE TITLE
Difference from demo

### ISSUE THREAD

**Issue by blackwaterbread** [lukemcdonald/holly-react#6]
Hello @lukemcdonald !

The result is different from the example when cloned and executed. What should I do? (attached a screenshot.)
would be very grateful if you could answer.

Sincerely,
dayrain

![lukemcdonald github io_holly-react_](https://user-images.githubusercontent.com/40688555/136931176-3572bf18-fd23-4b84-ae3c-c5209bdedbe7.png)
![localhost_3000_holly-react](https://user-images.githubusercontent.com/40688555/136931180-5170d133-c9e0-40fe-bac9-b648c786c510.png)
.

**Comment by lukemcdonald** [comment]
Hi, @blackwaterbread! Thanks for taking the time to point this out. I had some time to update a few things today and improving the styles was one of them.
