### ISSUE TITLE
[BUG]: npm start throws error 

### ISSUE THREAD

**Issue by VibinKesavan** [lukemcdonald/holly-react#7]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues.

### Description of the bug

Looking for directory that doesn't exists and fails when running npm start 

PS C:\git\testapp\app> npm start

> holly_react@0.1.0 start
> NODE_PATH=./src npm-run-all -p watch:css start:js

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
PS C:\git\testapp\app> npm start

> holly_react@0.1.0 start
> npm-run-all -p watch:css start:js

> holly_react@0.1.0 start:js
> react-scripts start

> holly_react@0.1.0 watch:css
> watch 'npm run build:css' src/assets/css/theme

> Watching run
> Watching build:css'
> Watching src/assets/css/theme
C:\git\testapp\app\node_modules\@cnakazawa\watch\main.js:73
    if (err) throw err;
             ^

[Error: ENOENT: no such file or directory, stat 'C:\git\testapp\app\run'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\git\\testapp\\app\\run'
}
ERROR: "watch:css" exited with 1.

### Steps to Reproduce

Clone repo 
npm install 
npm start

### Additional Information

None

**Comment by lukemcdonald** [comment]
Hi, @VibinKesavan! Thanks for the bug report. I had time to come back to this project and update a few things. I believe things should be working for you now.
